### ISSUE TITLE
The memcpy call in fastio is undefined behavior

### ISSUE THREAD

**Issue by algmyr** [NyaanNyaan/library#13]
https://github.com/NyaanNyaan/library/blob/daca0f7dd93570e4717701d9332042695595cd09/misc/fastio.hpp#L28

`memcpy(dst, src, n)` assumes that memory regions `[dst, dst+n)` and `[src, src+n)` do **not** overlap. This might not be the case for this code, which is easy to verify if you compile with sanitizers `-fsanitize=address,undefined` and run it with some problem. To avoid UB you want `memmove`, though it might have some minor performance implications.

**Comment by NyaanNyaan** [comment]
Thanks for reporting an issue! I didn't notice the UB because I wasn't using sanitizers.
I've decided to use `memmove` because `memmove` implementation in gcc is the same as `memcpy` when regions do not overlap.
(There will be a few more conditional branches, but I think it will have no effect on performance.)
